# === Основні налаштування середовища ===
[env]
TERM = "xterm-256color"  # Тип термінала для сумісності з TUI-додатками.

# === Налаштування вікна ===
[window]
padding.x = 20            # Відступи по горизонталі.
padding.y = 20            # Відступи по вертикалі.
dimensions = { columns = 100, lines = 25 }  # Розмір вікна за замовчуванням.
decorations = "none"      # Тип обрамлення вікна: "full", "none", або "buttonless".
opacity = 0.95            # Прозорість вікна.
# blur = true             # Увімкнення розмиття (працює тільки на macOS/KDE Wayland).

# === Налаштування шрифтів ===
[font]
normal.family = "UbuntuMono Nerd Font"  # Основний шрифт.
size = 17.0                             # Розмір шрифту.

# === Основні кольори ===
[colors.primary]
background = "#282933"  # Колір фону.
foreground = "#ffffff"  # Колір тексту.

# === Звичайні кольори ===
[colors.normal]
black   = "#3b4252"  # Звичайний чорний.
red     = "#fe6969"  # Звичайний червоний.
green   = "#50fa7b"  # Звичайний зелений.
yellow  = "#f0f98c"  # Звичайний жовтий.
#blue    = "#178dc9"  # Звичайний синій.
blue    = "#bd93f9"  # Звичайний синій.
magenta = "#b48ead"  # Звичайний магента.
cyan    = "#88c0d0"  # Звичайний блакитний.
white   = "#ffffff"  # Звичайний білий.

# === Яскраві кольори ===
[colors.bright]
black   = "#4c566a"  # Яскравий чорний.
red     = "#fe6969"  # Яскравий червоний.
green   = "#50fa7b"  # Яскравий зелений.
yellow  = "#f0f98c"  # Яскравий жовтий.
blue    = "#81a1c1"  # Яскравий синій.
magenta = "#b48ead"  # Яскравий магента.
cyan    = "#8fbcbb"  # Яскравий блакитний.
white   = "#ffffff"  # Яскравий білий.

# === Кольори виділення ===
[colors.selection]
text = "#b2c6e8"        # Колір тексту у виділенні.
background = "#475b82"  # Колір фону у виділенні.

# === Кольори курсора ===
[colors.cursor]
text = "#2e3440"    # Колір тексту під курсором.
cursor = "#afc6f9"  # Колір курсора.

# === Налаштування миші ===
[mouse]
hide_when_typing = false  # Не приховувати курсор миші під час введення тексту.

# === Налаштування виділення ===
[selection]
save_to_clipboard = true  # Копіювати виділений текст у системний буфер обміну.

# === Налаштування командної оболонки ===
[shell]
program = "/bin/fish"  # Основна оболонка (можна вказати bash, zsh тощо).

# === Налаштування курсора ===
[cursor]
style = { shape = "Block", blinking = "On" }  # Стиль основного курсора.
vi_mode_style = "None"                        # Стиль курсора для режиму vi.

# === Налаштування клавіатури ===
[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },  # Ctrl+Shift+N для створення нового вікна.
    { key = "C", mods = "Control", action = "Copy" },                   # Ctrl+C для копіювання в буфер обміну.
    { key = "V", mods = "Control", action = "Paste" },                  # Ctrl+V для вставки з буфера обміну.
]

